MVC_Onion_Project.Presentetion/Controllers/AuthorController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Onion_Project.Application.DTO_s;
using MVC_Onion_Project.Application.DTO_s.AuthorDTO_s;
using MVC_Onion_Project.Application.Services.AuthorService;
using MVC_Onion_Project.Application.Services.CategoryService;
using MVC_Onion_Project.Presentation.Models.AuthorVM_s;
using MVC_Onion_Project.Presentation.Models.CategoryVM_s;

namespace MVC_Onion_Project.Presentation.Controllers
{
    public class AuthorController : BaseController
    {
        private readonly IAuthorService _authorService;


        public AuthorController(IAuthorService authorService, IMapper mapper, INotyfService notifyService) : base(notifyService, mapper)
        {
           _authorService = authorService;

        }

        // GET: AuthorController
        public async Task<IActionResult> Index()
        {
            var result = await _authorService.GetAllAsync();

            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return View(_mapper.Map<List<AuthorListVM>>(result.Data));
            }
            var authorList = _mapper.Map<List<AuthorListVM>>(result.Data);
            SuccessNotification(result.Message);

            return View(authorList);
            
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _authorService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return View(_mapper.Map<AuthorDetailVM>(result.Data));
            }
            SuccessNotification(result.Message);

            var categoryDetailVm = _mapper.Map<AuthorDetailVM>(result.Data);
            return View(categoryDetailVm);
        }



        // GET: AuthorController/Create
        public ActionResult Create()
        {
            AuthorCreateVM authorCreateVm = new AuthorCreateVM()
            {
                DateofBirth = DateTime.Now
            };

            return View(authorCreateVm);
        }

        // POST: AuthorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorCreateVM authorCreateVM)
        {
            if (!ModelState.IsValid)
            {

                return View(authorCreateVM);
            }
            var authorCreateDTO = _mapper.Map<AuthorCreateDTO>(authorCreateVM);
            var result = await _authorService.AddAsync(authorCreateDTO);

            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return View(_mapper.Map<AuthorCreateVM>(result.Data));

            }
            SuccessNotification(result.Message);

            var authorCreatevm = _mapper.Map<AuthorCreateVM>(result.Data);

            return RedirectToAction(nameof(Index));

        }



        // GET: AuthorController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var result = await _authorService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return RedirectToAction(nameof(Index));
            }

            return View(_mapper.Map<AuthorEditVM>(result.Data));
        }

        // POST: AuthorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AuthorEditVM authorUpdateVm)
        {
            if (!ModelState.IsValid)
            {
                return View(authorUpdateVm);
            }
            var result = await _authorService.UpdateAsync(_mapper.Map<AuthorEditDTO>(authorUpdateVm));
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNotification(result.Message);
            return RedirectToAction(nameof(Index));
        }

        // GET: AuthorController/Delete/5
        public async Task <ActionResult> Delete(Guid id)
        {
            var result = await _authorService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNotification(result.Message);
            return RedirectToAction(nameof(Index));
        }



       
    }
}

MVC_Onion_Project.Presentetion/Controllers/BookController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AspNetCoreHero.ToastNotification.Notyf;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Onion_Project.Application.DTO_s.AuthorDTO_s;
using MVC_Onion_Project.Application.DTO_s.BookDTO_s;
using MVC_Onion_Project.Application.DTO_s.CategoriesBooksDTO_s;
using MVC_Onion_Project.Application.Services.AuthorService;
using MVC_Onion_Project.Application.Services.BookService;

using MVC_Onion_Project.Application.Services.CategoryService;
using MVC_Onion_Project.Domain.Utilities.Concrete;
using MVC_Onion_Project.Infrastructure.Repositories.Concreates;
using MVC_Onion_Project.Infrastructure.Repositories.Interfaces;
using MVC_Onion_Project.Presentation.Models.AuthorVM_s;
using MVC_Onion_Project.Presentation.Models.BookVM_s;
using MVC_Onion_Project.Presentation.Models.CategoriesBooksVM;
using NuGet.Packaging.Signing;
using System.Collections.Generic;

namespace MVC_Onion_Project.Presentation.Controllers
{
    public class BookController : BaseController
    {
        private readonly IBookService _bookService;
        private readonly ICategoryService _categoryService;


        public BookController(IBookService bookService, IAuthorService authorService, ICategoryService categoryService, IMapper mapper, INotyfService notifyService) : base(notifyService, mapper)
        {
            _bookService = bookService;
            _authorService = authorService;
            _categoryService = categoryService;

        }

        private readonly IAuthorService _authorService;

        public async Task<IActionResult> Index()
        {
           var result= await _bookService.GetAllAsync();

            SuccessNotification(result.Message);

            return View(_mapper.Map<List<BookListVM>>(result.Data));
        }

        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _bookService.GetByIdAsync(id);
            var detailvm = _mapper.Map<BookDetailVM>(result.Data);
            detailvm.CategoryList = await GetCategoryNameSelectListAsync(result.Data.SelectedCategoryIds);
            if (!result.IsSuccess)
            {

                ErrorNotification(result.Message);

                return View(detailvm);
            }
            SuccessNotification(result.Message);

            return View(detailvm);

        }

        public async Task<IActionResult> Create()
        {

            BookCreateVM vm = new BookCreateVM()
            {
                AuthorList=await GetAuthorSelectListAsync(),
                CategoryList=await GetCategorySelectListAsync(),
            };


            return View(vm);

        }




        [HttpPost]
        public async Task<IActionResult> Create(BookCreateVM bookCreateVM)
        {
            if (!ModelState.IsValid)
            {
                return View(bookCreateVM);

            }
            var result = await _bookService.AddAsync(_mapper.Map<BookCreateDTO>(bookCreateVM));
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(Guid id)
        {

            var result = await _bookService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return RedirectToAction(nameof(Index));
            }
            var bookeditvm = _mapper.Map<BookEditVM>(result.Data);

			bookeditvm.AuthorList = await GetAuthorSelectListAsync();
            bookeditvm.CategoryList = await GetCategorySelectListAsync();
            SuccessNotification(result.Message);

			return View(bookeditvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookEditVM bookEditVM)
        {
            if (!ModelState.IsValid)
            {
                return View(bookEditVM);
            }
            var result = await _bookService.UpdateAsync(_mapper.Map<BookEditDTO>(bookEditVM));
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNotification(result.Message);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _bookService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return RedirectToAction(nameof(Index));
            }
            SuccessNotification(result.Message);

            return RedirectToAction(nameof(Index));
        }


        private async Task<SelectList> GetAuthorSelectListAsync()
        {
            var authors = await _authorService.GetAllAsync();

            return new SelectList(authors.Data.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name + " " + x.Surname
            }), "Value", "Text");

        }
        private async Task<SelectList> GetCategorySelectListAsync()
        {
            var categories = await _categoryService.GetAllAsync();
            return new SelectList(categories.Data.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name

            }), "Value", "Text");
        }
        private async Task<SelectList> GetCategoryNameSelectListAsync(List<Guid> ids)
        {
            var categories = await _categoryService.GetByIdsAsync(ids);
            return new SelectList(categories.Data.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name

            }), "Value", "Text");
        }



    }


}

MVC_Onion_Project.Presentetion/Controllers/CategoryController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC_Onion_Project.Application.DTO_s;
using MVC_Onion_Project.Application.Services.CategoryService;
using MVC_Onion_Project.Domain.Entities;
using MVC_Onion_Project.Domain.Utilities.Concrete;
using MVC_Onion_Project.Presentation.Models.CategoryVM_s;


namespace MVC_Onion_Project.Presentation.Controllers
{
    public class CategoryController : BaseController
    {

        private readonly ICategoryService _categoryService;


        public CategoryController(ICategoryService categoryService, IMapper mapper, INotyfService notifyService) :base(notifyService, mapper)
        {
            _categoryService = categoryService;

        }


        // GET: CategoryController
        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.OrderByNameGetAllAsync();
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);
                return View(_mapper.Map<List<CategoryListVM>>(result.Data));
            }
            var categoryList= _mapper.Map<List<CategoryListVM>>(result.Data);
            SuccessNotification(result.Message);

            return View(categoryList);
        }

        //GET: CategoryController/Details/5
     
        public async Task<IActionResult> Details(Guid id)
        {            
            var result = await _categoryService.GetByIdAsync(id);

            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return View(_mapper.Map<CategoryDetailVM>(result.Data));
            }
            SuccessNotification(result.Message);

            var categoryDetailVm = _mapper.Map<CategoryDetailVM>(result.Data);
            return View(categoryDetailVm);

        }

        //GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryCreateVM categoryCreateVM)
        {
            if (!ModelState.IsValid)
            { 
                return View(categoryCreateVM);
            }
            var categoryCreateDTO = _mapper.Map<CategoryCreateDTO>(categoryCreateVM);
            var result = await _categoryService.AddAsync(categoryCreateDTO);

            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return View(_mapper.Map<CategoryCreateVM>(result.Data));

            }
            SuccessNotification(result.Message);

            var categoryCreatevm = _mapper.Map<CategoryCreateVM>(result.Data);

            return RedirectToAction(nameof(Index));

        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var result = await _categoryService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return View(_mapper.Map<CategoryEditVM>(result.Data));
            }
            var categoryEditVm = _mapper.Map<CategoryEditVM>(result.Data);
            return View(categoryEditVm);

        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CategoryEditVM categoryEditVM)
        {
            if (!ModelState.IsValid)
            {

                return View(categoryEditVM);
            }
            var categoryeditdto = _mapper.Map<CategoryEditDTO>(categoryEditVM);
            var result = await _categoryService.UpdateAsync(categoryeditdto);
            if (!result.IsSuccess)
            {
                ErrorNotification(result.Message);

                return RedirectToAction(nameof(Index));

			}
            SuccessNotification(result.Message);

            var resultVM = _mapper.Map<CategoryEditVM>(result.Data);
            return RedirectToAction(nameof(Index));

        }

        // GET: CategoryController/Delete/5
        public async Task<ActionResult> Delete(Guid id)
        {
            
            var result = await _categoryService.DeleteAsync(id);
            if (!result.IsSuccess) 
            {
                ErrorNotification(result.Message);

                return RedirectToAction(nameof(Index));
			}
            //SuccessNotification(result.Message);

            return RedirectToAction(nameof(Index));
            
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<IActionResult> SortedCategories()
        {
         return View();
        }

    }
}

MVC_Onion_Project.Presentetion/Views/Shared/_Layout.cshtml
@{
    var messageFromServer = TempData["MessageFromServer"] as string;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>

        
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link href="~/toastr.min.css" rel="stylesheet" />

  
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" asp-controller="Home" asp-action="Index">
                <img src="~/assets/img/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">MainPage</span>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link " asp-controller="Category" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-single-copy-04 text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Categories</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-controller="Author" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-danger text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Authors</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " asp-controller="Book" asp-action="Index">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-single-copy-04 text-info text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Books</span>
                    </a>
                </li>
      
            </ul>
    
    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
            <div class="container-fluid py-1 px-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                        <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
                        <li class="breadcrumb-item text-sm text-white active" aria-current="page">Dashboard</li>
                    </ol>
                </nav>
            </div>
        </nav>
        <!-- End Navbar -->
        <div class="container-fluid py-4">
     @RenderBody()
           
        </div>
    </main>
    <div class="fixed-plugin">
        <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
            <i class="fa fa-cog py-2"> </i>
        </a>
        <div class="card shadow-lg">
            <div class="card-header pb-0 pt-3 ">
                <div class="float-start">
                    <h5 class="mt-3 mb-0">Argon Configurator</h5>
                    <p>See our dashboard options.</p>
                </div>
                <div class="float-end mt-4">
                    <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
                        <i class="fa fa-close"></i>
                    </button>
                </div>
                <!-- End Toggle Button -->
            </div>
            <hr class="horizontal dark my-1">
            <div class="card-body pt-sm-3 pt-0 overflow-auto">
                <!-- Sidebar Backgrounds -->
                <div>
                    <h6 class="mb-0">Sidebar Colors</h6>
                </div>
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors my-2 text-start">
                        <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
                        <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
                    </div>
                </a>
                <!-- Sidenav Type -->
                <div class="mt-3">
                    <h6 class="mb-0">Sidenav Type</h6>
                    <p class="text-sm">Choose between 2 different sidenav types.</p>
                </div>
                <div class="d-flex">
                    <button class="btn bg-gradient-primary w-100 px-3 mb-2 active me-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
                    <button class="btn bg-gradient-primary w-100 px-3 mb-2" data-class="bg-default" onclick="sidebarType(this)">Dark</button>
                </div>
                <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
                <!-- Navbar Fixed -->
                <div class="d-flex my-3">
                    <h6 class="mb-0">Navbar Fixed</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
                    </div>
                </div>
                <hr class="horizontal dark my-sm-4">
                <div class="mt-2 mb-5 d-flex">
                    <h6 class="mb-0">Light / Dark</h6>
                    <div class="form-check form-switch ps-0 ms-auto my-auto">
                        <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
                    </div>
                </div>
                <a class="btn bg-gradient-dark w-100" href="https://www.creative-tim.com/product/argon-dashboard">Free Download</a>
                <a class="btn btn-outline-dark w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/license/argon-dashboard">View documentation</a>
                <div class="w-100 text-center">
                    <a class="github-button" href="https://github.com/creativetimofficial/argon-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/argon-dashboard on GitHub">Star</a>
                    <h6 class="mt-3">Thank you for sharing!</h6>
                    <a href="https://twitter.com/intent/tweet?text=Check%20Argon%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fargon-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                        <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
                    </a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/argon-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
                        <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/chartjs.min.js"></script>

    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
   
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/argon-dashboard.min.js?v=2.0.4"></script>
	<script src="~/js/deletepopup.js"></script>

    @await Component.InvokeAsync("Notyf")

</body>

</html>